// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Verdant - Invasive Plants",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Verdant - Invasive Plants",
            targets: ["AppModule"],
            bundleIdentifier: "com.NouraAlshathry.Verdant",
            teamIdentifier: "F7RR3WPWYP",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education,
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("plants.json"),
                .copy("PlantClassifier.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)